<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kristie Campana">

<title>10&nbsp; Factorial Designs – Statistics for Social Scientists Who Are A Little Afraid of Them</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter10.html" rel="next">
<link href="./chapter8.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-3e54a2ba524a9c641b796d074eb695a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter9.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial Designs</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics for Social Scientists Who Are A Little Afraid of Them</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction: Why Write This Book?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fundamentals of Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Samples and Populations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Understanding Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Getting to Know Your Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">T-Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Between-Subject ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Within-Subject ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter9.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Non-Parametric Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Correlations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Mediation and Moderation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Appendix 1: Tables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#chapter-9-factorial-designs" id="toc-chapter-9-factorial-designs" class="nav-link active" data-scroll-target="#chapter-9-factorial-designs"><span class="header-section-number">11</span> Chapter 9: Factorial Designs</a>
  <ul class="collapse">
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives"><span class="header-section-number">11.1</span> Learning Objectives</a></li>
  <li><a href="#a-two-way-anova" id="toc-a-two-way-anova" class="nav-link" data-scroll-target="#a-two-way-anova"><span class="header-section-number">11.2</span> A Two Way ANOVA</a></li>
  <li><a href="#a-brief-note-on-n-way-anovas" id="toc-a-brief-note-on-n-way-anovas" class="nav-link" data-scroll-target="#a-brief-note-on-n-way-anovas"><span class="header-section-number">11.3</span> A Brief Note on N-Way ANOVAs</a>
  <ul class="collapse">
  <li><a href="#what-to-do-if-your-assumption-of-normality-andor-homoscedasticity-are-violated" id="toc-what-to-do-if-your-assumption-of-normality-andor-homoscedasticity-are-violated" class="nav-link" data-scroll-target="#what-to-do-if-your-assumption-of-normality-andor-homoscedasticity-are-violated"><span class="header-section-number">11.3.1</span> What to do if your assumption of normality and/or homoscedasticity are violated</a></li>
  <li><a href="#calculating-an-effect-size-for-between-subject-t-tests" id="toc-calculating-an-effect-size-for-between-subject-t-tests" class="nav-link" data-scroll-target="#calculating-an-effect-size-for-between-subject-t-tests"><span class="header-section-number">11.3.2</span> Calculating an Effect Size for Between-Subject T-Tests</a></li>
  </ul></li>
  <li><a href="#writing-the-results-of-a-factorial-anova" id="toc-writing-the-results-of-a-factorial-anova" class="nav-link" data-scroll-target="#writing-the-results-of-a-factorial-anova"><span class="header-section-number">11.4</span> Writing the Results of a Factorial ANOVA</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial Designs</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kristie Campana </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="chapter-9-factorial-designs" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Chapter 9: Factorial Designs</h1>
<section id="learning-objectives" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">11.1</span> Learning Objectives</h2>
<ul>
<li>Know what a factorial is and what types of data it requires.</li>
<li>Know the assumptions of a factorial ANOVA.</li>
<li>Know how to interpret main effects and interactions in a factorial design.</li>
<li>How to write up the results of a factorial ANOVA.</li>
</ul>
<p>Now that we have the basics of an ANOVA down, we can build to a more complex design – the factorial ANOVA. In this technique, we are now adding another independent variable to see how two (or more) variables influence a particular outcome.</p>
</section>
<section id="a-two-way-anova" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="a-two-way-anova"><span class="header-section-number">11.2</span> A Two Way ANOVA</h2>
<p>As an example, let’s say that we want to examine several different time management techniques for college students: Pomodoro technique, Eisenhower matrix, and Time blocking. However, perhaps we also believe that which technique works might depend on whether the student is majoring in a STEM field versus a Humanities field. We get a sample of students in both STEM and Humanities, and assign them to the three different techniques. You can see the data for this in the Time management file.</p>
<p>This is a factorial design. We can also describe it as a “two-way” ANOVA, because we have two independent variables. We might also see it described as a 2x3 ANOVA (we have one variable, or “factor,” with two levels, and a second variable with three levels).</p>
<p>So, you may be asking why we don’t just do two separate ANOVAs for each variable? One reason is, again, <strong>family-wise error.</strong> But a more important issue is something known as an <strong>interaction.</strong> In research like this, we sometimes find that the influence of of one independent variable is affected by the other independent variable. I’ll share more about what interactions look like in a moment.</p>
<p>The good news is that, mathematically, a factorial ANOVA is very similar to the one-way ANOVA we’ve worked with so far. So, just as before, we need to understand how much total variance is in our model, and we do this by comparing each data point to the grand mean:</p>
<p><span class="math inline">\(SS_{Total}=\sum^{N}_{i=1}(x_i-\bar{{x}}_{grand})^2\)</span></p>
<p>And just as before, we can also partial some of the variance into the sum of squares model, which describes how much variance is explained by group membership. But we have to remember that there are now two independent variables, so some of the variance in this model is explained by the technique the student uses, and some of it is explained by their major, so we now have two equations we need to use:</p>
<p><span class="math inline">\(SS_{tech}=\sum^{k}_{g=1}n_{tech}(x_{tech}-\bar{{x}}_{grand})^2\)</span></p>
<p>So, for the sum of squares attributed to technique, we take the average for each group and compare it to the grand mean. Likewise:</p>
<p><span class="math inline">\(SS_{maj}=\sum^{k}_{g=1}n_{maj}(x_{maj}-\bar{{x}}_{grand})^2\)</span></p>
<p>For the majors, we take the average of each of our two major groups and compare it to the grand mean. So far, this looks a lot like what we’ve done so far. But we have one additional piece of model variance we need to attend to:</p>
<p><span class="math inline">\(SS_{cell}=\sum^{k}_{g=1}n_{cell}(x_{cell}-\bar{{x}}_{grand})^2\)</span></p>
<p>In this data, we have 6 different groups (STEM/Pomodoro; Humanities/Pomodoro; STEM/Eisenhower…) and each of these groups have their own mean. These means tell us a little something about differences that aren’t completely explained by someone’s group membership on both variables… there seems to be something extra here. That little extra something is the interaction. Mathematically, any variance from these cells that isn’t attributed to our independent variables is the interaction effect:</p>
<p><span class="math inline">\(SS_{tech \times maj}= SS_{cell} - SS_{tech} - SS_{maj}\)</span></p>
<p>If you look at <a href="#fig-twoway" class="quarto-xref">Figure&nbsp;<span>11.1</span></a>, you’ll see that what technique works best depends upon whether a student is a STEM major or a Humanities major. That’s what interactions are all about – sometimes the combinations between our independent variables yield interesting results like this. So, the factorial ANOVA allows us to look at these interactions in a way two one-way ANOVAs don’t.</p>
<div id="fig-twoway" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A graph that shows the Pomodoro technique works well for both majors, while Esienhower is best for STEM students and Time Block is best for Humanities students">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-twoway-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/twoway.png" class="img-fluid figure-img" alt="A graph that shows the Pomodoro technique works well for both majors, while Esienhower is best for STEM students and Time Block is best for Humanities students">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-twoway-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.1: A figure of the two-way ANOVA
</figcaption>
</figure>
</div>
<p>Finally, as you know, our data will contain some differences that we simply can’t explain, so we also have a residual sum of squares, calculated similarly to how we do it in a one-way ANOVA:</p>
<p><span class="math inline">\(SS_{Resid.}=SS_{Total} - SS_{cells}\)</span></p>
<p>If you recall from Chapter 7, we then go through the task of calculating degrees of freedom and mean squares. However, with a one-way ANOVA, we had only one F ratio we were interested in. Now, we have three: the <strong>main effect</strong> of technique, the <strong>main effect</strong> of major, and the <strong>interaction</strong> between technique and major. These three effects can occur in any combination – maybe they are all significant, maybe we have main effects and no interaction, or maybe we have no main effects but we have an interaction.</p>
<p>In this particular data set, we have the following results:</p>
<div id="tbl-twoway" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-twoway-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.1: F-test results. These results were generated using R; results from SPSS are slightly different.
</figcaption>
<div aria-describedby="tbl-twoway-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>df</th>
<th>SS</th>
<th>MS</th>
<th>F-value</th>
<th>Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Major</td>
<td>1</td>
<td>.08</td>
<td>.075</td>
<td>.039</td>
<td>.84</td>
</tr>
<tr class="even">
<td>Technique</td>
<td>2</td>
<td>18.98</td>
<td>9.49</td>
<td>4.98</td>
<td>.008</td>
</tr>
<tr class="odd">
<td>Major x Technique</td>
<td>2</td>
<td>209.95</td>
<td>104.97</td>
<td>55.12</td>
<td>&lt;.001</td>
</tr>
<tr class="even">
<td>Residuals</td>
<td>114</td>
<td>217.12</td>
<td>1.91</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>This means we have a main effect of technique, no main effect of major, and an interaction. In fact, <a href="#fig-twoway" class="quarto-xref">Figure&nbsp;<span>11.1</span></a> demonstrates nicely what is going on – on average, different majors perform roughly the same. We also see some differences in how techniques work. But perhaps most importantly, we see the type of technique that’s most effective depends on what major a student is earning – if a student is getting a STEM degree, the Eisenhower matrix is most helpful for time management, while if a student is getting a Humanities degree, Time blocking is the most helpful.</p>
<p>As you might imagine, a factorial ANOVA is similar to a one-way ANOVA in that it only tells us if one group is significantly different from another group. For this result, we’d want to conduct a contrast or a post-hoc test on the techniques to see which groups are significantly higher than which. We didn’t see a main effect of major, but even if we had, there are only two groups, so we know where the difference is and there’s no need for a post-hoc test.</p>
<p>As for interactions, there isn’t exactly a way to easily test where the big differences are in an interactions. Instead, if you are curious about whether there are significant differences, you can conduct a <strong>simple effect analysis</strong>. This is where you take a “slice” of the data on one variable, and examine what’s going on. For example, we could ask “For STEM majors, what technique is the best?” Alternatively, you could take cell means and compare them with a t-test. For example, we could compare the STEM/Pomodoro group to the Humanities/Eisenhower group. Keep in mind that you should use a Bonferroni correction for each comparison, so this technique is best for answering specific questions about the data – to compare every group, we’d need 15 t-tests, which is quite a lot. So, using t-tests for examining interactions is most appropriate when you have specific comparisons you’d like to probe.</p>
</section>
<section id="a-brief-note-on-n-way-anovas" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="a-brief-note-on-n-way-anovas"><span class="header-section-number">11.3</span> A Brief Note on N-Way ANOVAs</h2>
<p>Two-way ANOVAs are not the limit for you! You can add more independent variables… but they get much harder to understand, and you need a large sample size (i.e., a lot of power) to find significant results.</p>
<p>Just to share one example of what this might look like, imagine that I am looking at customer reactions to store clerks. I set up a study where I have two genders of shoppers (men and women), two genders of store clerks (men and women), and two different types of stores the shoppers go to (a clothing store and a computer store).</p>
<p>Because we have three independent variables (customer gender, clerk gender, store type) this is a three-way ANOVA (and specifically, we could call it a <span class="math inline">\(2 \times 2 \times 2\)</span> ANOVA (three variables, with two levels each).</p>
<p>This now means our results are also going to me more complex. We will ultimately have:</p>
<ul>
<li><p>A main effect of customer gender</p></li>
<li><p>A main effect of clerk gender</p></li>
<li><p>A main effect of store type</p></li>
<li><p>A two-way interaction between customer and client genders</p></li>
<li><p>A two-way interaction between customer and store type</p></li>
<li><p>A two-way interaction between client gender and store type</p></li>
<li><p>A three-way interaction between client gender, customer gender, and store type</p></li>
</ul>
<p>It gets complicated fast! So, you don’t see a lot of research that goes beyond a three-way ANOVA, but it certainly is possible to create more complex models. One difficulty with a three-way ANOVA like this is that it’s difficult to clearly convey the results. Really, we’d need a 3D graph to be able to put all three predictors into one graph, but those tend to be hard to understand. So instead, we’d probably need to break our charts into two 2D graphs.</p>
<div id="fig-threeway" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two bar graphs, one for clothing stores and one for computer stores. Graphs show that the store type, clerk gender, and customer gender all affect customer service. The lowest customer service is experienced by female customers in a computer store by female clerks.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-threeway-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/genderstore.png" class="img-fluid figure-img" alt="Two bar graphs, one for clothing stores and one for computer stores. Graphs show that the store type, clerk gender, and customer gender all affect customer service. The lowest customer service is experienced by female customers in a computer store by female clerks.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-threeway-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.2: A graph of a 2x2x2 ANOVA result
</figcaption>
</figure>
</div>
<p>Likewise, most people find two-way interactions a little complex to talk about; three-way interactions even are more difficult, so sometimes these analyses get complex enough that it can be hard to translate the practical implications to other people. Imagine trying to explain in words all the things going on in <a href="#fig-threeway" class="quarto-xref">Figure&nbsp;<span>11.2</span></a>. It’s not impossible, but it’s worth nothing here that adding even one additional independent variable makes the results much more complex to interpret in practical terms.</p>
<section id="what-to-do-if-your-assumption-of-normality-andor-homoscedasticity-are-violated" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="what-to-do-if-your-assumption-of-normality-andor-homoscedasticity-are-violated"><span class="header-section-number">11.3.1</span> What to do if your assumption of normality and/or homoscedasticity are violated</h3>
<p>Most programs don’t allow for easy correction of this problem, but if you have concerns about these issues, we can again apply a <strong>Welch test</strong>, just like we did for a one-way between-subject ANOVA<strong>.</strong> For the most part, though, ANOVAs are generally robust so most of the time, violations of these assumptions are not a major concern.</p>
</section>
<section id="calculating-an-effect-size-for-between-subject-t-tests" class="level3" data-number="11.3.2">
<h3 data-number="11.3.2" class="anchored" data-anchor-id="calculating-an-effect-size-for-between-subject-t-tests"><span class="header-section-number">11.3.2</span> Calculating an Effect Size for Between-Subject T-Tests</h3>
<p>I bet you know where I’m going this this… if you need an effect size, the best option is <span class="math inline">\(\hat{\omega}^2\)</span> . You can calculate this for each main effect and any interactions. Here’s the equation once again:</p>
<p><span class="math inline">\(\hat{\omega}^2=\frac{SS_M-(df_M)MS_R}{SS_T+MS_R}\)</span></p>
</section>
</section>
<section id="writing-the-results-of-a-factorial-anova" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="writing-the-results-of-a-factorial-anova"><span class="header-section-number">11.4</span> Writing the Results of a Factorial ANOVA</h2>
<p>Because you are conveying so much information when you do a factorial design, I strongly recommend you use a figure (or at the very least, a table) to help your audience understand the data. Just reporting a main effect or interaction as significant doesn’t help your audience understand how these effects look; a figure is the most efficient way of communicating this, as it provides a visual summary of all the group means very quickly. If you opt not to use a figure, you are going to need to report a lot of means and standard deviations!</p>
<p>When sharing the results of a between-subject ANOVA, you want to convey several pieces of information to your audience:</p>
<ul>
<li><p>How many independent variables you are using in the model, and how many levels each factor has. This can be efficiently conveyed by using the notation I’ve used in this chapter (e.g., a <span class="math inline">\(2\times3\)</span> ANOVA) but you can also describe the nature of your variables in more detail.</p></li>
<li><p>What the average scores are for each group and their accompanying standard deviations;</p></li>
<li><p>For all main effects and interactions, you must provide the F-test value, its degrees of freedom, and its significance;</p></li>
<li><p>Any simple effects, constrasts, or post-hoc tests you use to further explain significant findings in your omnibus test.</p></li>
</ul>
<p>Here are some examples of how we might explain the results of the analyses we’ve discussed in the chapter:</p>
<blockquote class="blockquote">
<p>According to a 2 x 3 ANOVA, there is a main effect of technique, <em>F</em>(2,114)=4.98, <em>p</em>=.001, such that the Pomodoro technique is significantly less helpful than Time blocking or Eisenhower matrix. There is no significant main effect of major, <em>F</em>(1,114)=.04, <em>p</em>=.84. There is a significant interaction, <em>F</em>(2,114)=55.12, <em>p</em>&lt;.001. As demonstrated by <a href="#fig-twoway" class="quarto-xref">Figure&nbsp;<span>11.1</span></a>, Time block is more helpful for Humanities majors, whereas Eisenhower matrix is more helpful for STEM majors.</p>
</blockquote>
<blockquote class="blockquote">
<p>According to a 2 x 2 x 2 ANOVA, there was a significant main effect for store type, <em>F</em>(1, 22)=23.40, <em>p</em>&lt;.001, with clothing stores having higher customer service. There was also a significant main effect for customer gender, <em>F</em>(1, 22)=18.91, <em>p</em>&lt;.001, with male customers receiving better customer service. There was no main effect for clerk gender, <em>F</em>(2, 22)=3.54, <em>p</em>=.07. I also found a significant interaction between store type and clerk gender, <em>F</em>(1, 22)=8.43, <em>p</em>=.008. Female clerks tended to demonstrate better customer service in clothing stores than they did in computer stores, while male clerks demonstrated better customer service in computer scores than they did in clothing stores. There was no interaction between clerk and customer gender, <em>F</em>(1, 22)=.02, <em>p</em>=.89. There was also no significant three-way interaction, <em>F</em>(1, 22)=1.86, <em>p</em>=.18. Results are presented in <a href="#fig-threeway" class="quarto-xref">Figure&nbsp;<span>11.2</span></a>.</p>
</blockquote>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter8.html" class="pagination-link" aria-label="Within-Subject ANOVA">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Within-Subject ANOVA</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter10.html" class="pagination-link" aria-label="Non-Parametric Tests">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Non-Parametric Tests</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>